#!/bin/bash
# Makes users
useradd -m clue
useradd -m entrance
useradd -m hall
useradd -m lounge
useradd -m ballroom
useradd -m diningroom
useradd -m kitchen
useradd -m billiardroom
useradd -m conservatory
useradd -m study
useradd -m cellar

# Makes passwords for each user
passwd -d clue
yes clue | passwd entrance
yes DDA0DD | passwd hall
yes orange | passwd lounge
yes trousers | passwd ballroom
yes blink182 | passwd diningroom
yes Sylphrapidash | passwd kitchen
yes Aardwolf | passwd billiardroom
yes 'dpa$$wor' | passwd conservatory
yes CONSTANCE | passwd study
passwd -d cellar

# Makes all of the scripts for each room
# Clue
echo "Welcome to Clue!" >> /home/clue/lookaround
echo "In Clue, you are a detective tasked with finding a murderer." >> /home/clue/lookaround
echo "To navigate through Clue, you change users on the linux command line." >> /home/clue/lookaround
echo "This is done through 'su (room)'." >> /home/clue/lookaround
echo "To change users, you will have to use a password cracking tool, such as hashcat to get the password for the room." >> /home/clue/lookaround
echo "To begin, type in 'su entrance' and the password 'clue'." >> /home/clue/lookaround
echo "Have fun!" >> /home/clue/lookaround
# Entrance
echo "You are greeted by Butler Wadsworth and are handed an enelope with your name across the front in cursive." >> /home/entrance/lookaround
echo "You open it and find only this written on a note: Dear Detective, if you wish to continue into the house, you will need the password." >> /home/entrance/lookaround
echo "'28bc8c78881b2f89bbeab4f9bb8fbeda'" >> /home/entrance/lookaround
echo "This appears familiar to you and you recollect that you've seen this type of MD5 hash before." >> /home/entrance/lookaround
echo "Can you figure out the password to enter the next room?" >> /home/entrance/lookaround
echo "Helpful commands: su, man, hashcat" >>/home/entrance/lookaround
# Hall
echo "As you enter the hall, you are greeted by the six suspects." >> /home/hall/lookaround
echo "Your sergeant informs you of their names: Col. Mustard, Mrs. Peacock, Mrs. White, Prof. Plum, Miss Scarlett, and Mr. Green." >> /home/hall/lookaround
echo "You give the suspects a look over before telling them to go to the room they were in at the time of the murder." >> /home/hall/lookaround
echo "You turn towards the lounge, heading to see the body, Mr. Boddy’s body that is, when a slip of paper on the floor catches your eye." >> /home/hall/lookaround
echo "Out of curiosity you bend down and pick it up and find the following scrawled across the note: 'e8c482645c1344206acfc8d47ebf6557'." >> /home/hall/lookaround
echo "You think you’ve seen this type of hash before when you were researching SHA hashes." >> /home/hall/lookaround
echo "It seems the lounge requires a password to enter, can you decode the note?" >> /home/hall/lookaround
echo "Helpful commands: su, man, hashcat -a 0 -m 100" >>/home/lounge/lookaround
# Lounge
echo "You enter a beautifully ornate lounge complete with a Persian rug, which was partly obstructed from view by a sprawled out dead body." >> /home/lounge/lookaround
echo "You slowly pace over to Mr. Boddy, when suddenly a burst of flames jump out from the fireplace." >> /home/lounge/lookaround
echo "You notice a few letters jutting out of the blaze." >> /home/lounge/lookaround
echo "Out of instinct you reach for them." >> /home/lounge/lookaround
echo "A few crumple into ashes in your hand, but you can still make out what was written on one of them: 'fe01d67a002dfa0f3ac084298142eccd'." >> /home/lounge/lookaround
echo "You decide to forgo inspecting Mr. Boddy’s body, but rather head to the ballroom." >> /home/lounge/lookaround
echo "But this door looks like it also needs a password...Maybe the letters from the flames can help?" >> /home/lounge/lookaround
echo "Helpful commands: su, man, hashcat -a 0" >>/home/lounge/lookaround
# Ballroom         
echo "You wander into a massive room with a lofted ceiling, and walls covered in elaborate paintings." >> /home/ballroom/lookaround
echo "In the middle of the dancefloor, softly swaying to imaginary music is Miss Scarlet." >> /home/ballroom/lookaround
echo "Her maroon dress complements the deep amber of the floors." >> /home/ballroom/lookaround
echo "You begin to ask her questions about what happened." >> /home/ballroom/lookaround
echo "You listen to her talk about their dinner party, or lack thereof as it appears Mr. Boddy died even before dinner was served, as the two of you walk around the room." >> /home/ballroom/lookaround
echo "You are paying more attention to the paintings then to her really, when one catches your eye." >> /home/ballroom/lookaround
echo "The sheer beauty of the painting completely pulls your attention away from Miss Scarlett." >> /home/ballroom/lookaround
echo "Who knew dogs playing poker could be so profound." >> /home/ballroom/lookaround
echo "But the painting is tilted!" >> /home/ballroom/lookaround
echo "You go to straighten it out but an envelope falls out." >> /home/ballroom/lookaround
echo "Scribbled across the top is: '1a637268f7aeb0186c899a6f0bb90aa7'." >> /home/ballroom/lookaround
echo "Inside you find a list of what you think are different dog breeds." >> /home/ballroom/lookaround
echo "Could you use this list to decode the password?" >> /home/ballroom/lookaround
echo "Maybe it's a hint as to who killed Mr. Boddy?" >> /home/ballroom/lookaround
echo "You decided to decode it before you head over to the diningroom." >> /home/ballroom/lookaround
echo "Helpful commands: su, man, hashcat -a 3" >>/home/ballroom/lookaround
# Dining Room
echo "It seems that Wadsworth is in the process of preparing dinner." >> /home/diningroom/lookaround
echo "You wander around the table and go to take a sip of the soup at your seat." >> /home/diningroom/lookaround
echo "But there is no spoon! Rather on the table lies a leap pipe." >> /home/diningroom/lookaround
echo "You look at the lead pipe for a second before deciding to use it as a straw and slurp up the soup." >> /home/diningroom/lookaround
echo "Hmm, the flavor reminds you of stone soup from the children’s book you loved as a child." >> /home/diningroom/lookaround
echo "You reach for the napkin on the table to dry off the pipe, but as you pick it up a notes falls out and lands in the soup." >> /home/diningroom/lookaround
echo "You fish it out quickly, but most of the writing has already dissolved." >> /home/diningroom/lookaround
echo "You can still make out this on the front: “6104df369888589d6dbea304b59a32d4” and a small note in the corner that you think says rockyou." >> /home/diningroom/lookaround
echo "You go to check out the kitchen but you notice a giant padlock on the door." >> /home/diningroom/lookaround
echo "Can you figure out the code? " >> /home/diningroom/lookaround
echo "Helpful commands: su, man, hashcat -a 3" >>/home/diningroom/lookaround
# Kitchen
echo "Upon entering the kitchen, you notice that it is empty of suspects." >> /home/kitchen/lookaround
echo "You spot a dog-eared cookbook for fruit pies lying on the counter, right next to a full rack of knives." >> /home/kitchen/lookaround
echo "Obviously Mr. Boddy was not stabbed with a knife! You decide to focus your energy on the pies." >> /home/kitchen/lookaround
echo "The cookbook looks well-loved and is dusted with flour." >> /home/kitchen/lookaround
echo "As you pick it up to find your favorite pie recipe(pumpkin!), a piece of paper flutters out from between the pages." >> /home/kitchen/lookaround
echo "In black ink it reads: 'fc369d54db02c2bfab6d354b6ced05f9' and 'billiardroom'." >> /home/kitchen/lookaround
echo "The hash looks familiar." >> /home/kitchen/lookaround
echo "You should be comfortable with this type of attack by now, but be warned, you might need to double your efforts for cracking it." >> /home/kitchen/lookaround
echo "Helpful commands: su, man, hashcat -a 3" >>/home/kitchen/lookaround
# Billiard Room
echo "In the billiard room, you find Col. Mustard playing a game of billiards." >> /home/billiardroom/lookaround
echo "Upon entering the room, the colonel takes it upon himself to tell you about his time in the army." >> /home/billiardroom/lookaround
echo "You begin to zone out as he rambles on until something strange catches your eye." >> /home/billiardroom/lookaround
echo "Sitting on the mantel was a candlestick holding the eight ball." >> /home/billiardroom/lookaround
echo "You move across the room and pick up the ball." >> /home/billiardroom/lookaround
echo "As you do, you notice something etched into the side of the ball: 'af5e7df14af034434124fd61b2b2b319'." >> /home/billiardroom/lookaround
echo "Holding the ball tentatively in your hand, you search the room for hints to solve this hash." >> /home/billiardroom/lookaround
echo "Hopefully you can solve it fast so that you can duck out on the colonel’s boring story and into the conservatory." >> /home/billiardroom/lookaround
echo "Helpful commands: su, man, hashcat -r" >>/home/billiardroom/lookaround
# Conservatory
echo "You knock on the door and then nope it, $tepping into the conservatory and are meet by Mr$. White." >> /home/conservatory/lookaround
echo "She lounges for uyo seductively dan you manage to jump tou of her way but unfortunately, you accidentally knock over a potted fern." >> /home/conservatory/lookaround
echo "The terracotta pot breaks and dirt spills over the floor." >> /home/conservatory/lookaround
echo "gLookin clo$er you see a folded scrap of paper under the leaves and $oil." >> /home/conservatory/lookaround
echo "You unfold it dan it reads: “4faa5c99cd33bc507e14f533f4cf2b48”." >> /home/conservatory/lookaround
echo "Solve this fast!" >> /home/conservatory/lookaround
echo "Apparently Mrs. White is on the lookout for husband #6!" >> /home/conservatory/lookaround
echo "You can escape to the study if you can $peed past Mrs. White and unlock the door." >> /home/conservatory/lookaround
echo "Dinosaur = rDino$aur" >> /home/conservatory/lookaround
echo "Helpful commands: su, man, hashcat -r" >>/home/conservatory/lookaround
# Study
echo "The floor creaks as you step into the study." >> /home/study/lookaround
echo "A huge desk occupies most of the space and the wood paneling of the walls is illuminated by the soft light of a lamp and the flicker of the fireplace." >> /home/study/lookaround
echo "A large oil painting of a General in uniform with an impressive moustache glares down at you." >> /home/study/lookaround
echo "Several ornate venetian masks are mounted on the walls, the purple paint and gold trim gleam in the warm light." >> /home/study/lookaround
echo "You notice a long rope laying across the desk." >> /home/study/lookaround
echo "As you pick up the rope, a layer of dust falls off it." >> /home/study/lookaround
echo "Obviously the rope has not been moved in a while." >> /home/study/lookaround
echo "The dust makes you sneeze and as you tilt your head, you notice that several letters are scattered across the windowsill, but only one has been opened. " >> /home/study/lookaround
echo "You turn over the ripped envelope and notice some text scribbled next the address line. " >> /home/study/lookaround
echo "It reads: “64b83bc470b544f57738f804d298c4be”. " >> /home/study/lookaround
echo "Could this be your next clue? Maybe this has something to do with Mr. Boddy’s CON? " >> /home/study/lookaround
echo "All this mystery really makes you want to step out for a breath of fresh air. " >> /home/study/lookaround
echo "Maybe the patio is where you head next..." >> /home/study/lookaround
echo "Helpful commands: su, man, hashcat -r" >>/home/study/lookaround
# Cellar
echo "You approach the cellar to confront the murderer." >> /home/cellar/lookaround
echo "You hear strange noises behind the door as you prepare to open it." >> /home/cellar/lookaround
echo "You take a deep breath and whip the door open." >> /home/cellar/lookaround
echo "You look up to find yourself face to face with Mr. Plum." >> /home/cellar/lookaround
echo "Helpful commands: " >>/home/cellar/lookaround

# Adds all of the users to log in to next
echo "The next room is the hall" >> /home/entrance/lookaround
echo "The next room is the lounge" >> /home/hall/lookaround
echo "The next room is the ballrooom" >> /home/lounge/lookaround
echo "The next room is the diningroom" >> /home/ballroom/lookaround
echo "The next room is the kitchen" >> /home/kitchen/lookaround
echo "The next room is the billiardroom" >> /home/billiardroom/lookaround
echo "The next room is the conservatory" >> /home/conservatory/lookaround
echo "The next room is the study" >> /home/study/lookaround
echo "The next room is the cellar" >> /home/cellar/lookaround

# Adds all of the hashed passwords
echo "28bc8c78881b2f89bbeab4f9bb8fbeda" > /home/entrance/hashedpassword
echo "e8c482645c1344206acfc8d47ebf6557" > /home/hall/hashedpassword
echo "fe01d67a002dfa0f3ac084298142eccd" > /home/lounge/hashedpassword
echo "1a637268f7aeb0186c899a6f0bb90aa7" > /home/ballroom/hashedpassword
echo "6104df369888589d6dbea304b59a32d4" > /home/diningroom/hashedpassword
echo "fc369d54db02c2bfab6d354b6ced05f9" > /home/kitchen/hashedpassword
echo "af5e7df14af034434124fd61b2b2b319" > /home/billiardroom/hashedpassword
echo "4faa5c99cd33bc507e14f533f4cf2b48" > /home/conservatory/hashedpassword
echo "64b83bc470b544f57738f804d298c4be" > /home/study/hashedpassword

# Changes permissions to make sure users can only access their own file
chmod 770 clue
chmod 770 entrance
chmod 770 hall
chmod 770 lounge
chmod 770 ballroom
chmod 770 diningroom
chmod 770 kitchen
chmod 770 billiardroom
chmod 770 conservatory
chmod 770 study
chmod 770 cellar

# Sets user to automatically go to home directory when they login
echo "cd" >> /home/clue/.bashrc
echo "cd" >> /home/entrance/.bashrc
echo "cd" >> /home/lounge/.bashrc
echo "cd" >> /home/ballroom/.bashrc
echo "cd" >> /home/diningroom/.bashrc
echo "cd" >> /home/kitchen/.bashrc
echo "cd" >> /home/billiardroom/.bashrc
echo "cd" >> /home/conservatory/.bashrc
echo "cd" >> /home/study/.bashrc
echo "cd" >> /home/cellar/.bashrc
